apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
    service: webserver
  name: giropops
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /giropops
      name: primeiro-volume
    resources:
      limits:
        cpu: "1"
        memory: "100Mi" # Limit 100Mi of RAM
      requests:
        cpu: "0.5" # Garanted 50% of 1 core
        memory: "50Mi" # Garanted 50Mi of RAM
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  

  volumes:
  - name: primeiro-volume
    emptyDir:
      sizeLimit: 256Mi # Limit 256Mi of RAM