apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
    service: webserver
  name: giropops
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      limits:
        cpu: "0.5" # Limit 50% of 1 core
        memory: "100Mi" # Limit 100Mi of RAM
      requests:
        cpu: "0.3" # Garanted 30% of 1 core
        memory: "50Mi" # Garanted 50Mi of RAM
  - image: ubuntu
    name: ubuntu
    args: ["sleep", "3600"]
    resources:
      limits:
        cpu: "0.5" # Limit 50% of 1 core
        memory: "100Mi" # Limit 100Mi of RAM
      requests:
        cpu: "0.3" # Garanted 30% of 1 core
        memory: "50Mi" # Garanted 50Mi of RAM
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
