apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
    service: webserver
  name: girus
spec:
  containers:
  - image: nginx
    name: nginx
  - image: busybox
    name: busybox
    args: ["sleep", "3600"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
